uwiger/gproc

- src/gproc.app.src
The comment says don't list applications which are load only,
just above the line listing stdlib which is load only.
It is very misleading to newcomers so best to remove it.
Sorry for the tiniest change ever but gproc is used by tons of newcomers and I figure it's best to avoid confusing them when they see this. :-)
> Remove misleading comment in .app file

- src/gproc_dist.erl
I have this crash report:
```erlang
2014-12-17 14:45:53 =ERROR REPORT====
** Generic leader gproc_dist terminating 
** Last message in was {pid_is_DOWN,<0.1845.0>}
** When Server state == {state,false,true,[]}
** Reason for termination == 
** {{case_clause,[]},[{gproc_dist,remove_entry,3,[{file,"src/gproc_dist.erl"},{line,733}]},{gproc_dist,maybe_failover,4,[{file,"src/gproc_dist.erl"},{line,701}]},{lists,foldl,3,[{file,"lists.erl"},{line,1261}]},{gproc_dist,process_globals,1,[{file,"src/gproc_dist.erl"},{line,674}]},{gproc_dist,handle_leader_cast,3,[{file,"src/gproc_dist.erl"},{line,649}]},{gen_leader,handle_msg,4,[{file,"src/gen_leader.erl"},{line,1169}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
2014-12-17 14:45:53 =CRASH REPORT====
crasher:
initial call: …
```
> Fix case_clause

- test/gproc_test_lib.erl
- test/gproc_tests.erl
This commit only adds tests for gproc_pool. 
Added extensive tests `test/gproc_pool:t_simple_pool/0` that includes creating a pool, adding, connecting, membership, disconnecting, removing, and pool deletion.
> added several pool tests to gproc_tests

- src/gproc_dist.erl
- test/gproc_test_lib.erl
- test/gproc_tests.erl
Fix some compiler warnings, and a bug which caused dist_test failure when adding a monitor from a non-leader node (a faulty return value in `gproc_dist:add_follow_to_waiters/5`).
> Uw intermittent test failures

- src/gproc_dist.erl
- test/gproc_dist_tests.erl
Addresses issues #87 #88 
There was no test case for global properties. Added one that checks replication of new properties as well as removal of property after process death.
> replication of prop deletes buggy

- src/gproc.erl
- src/gproc_bcast.erl
- src/gproc_int.hrl
- src/gproc_lib.erl
- test/gproc_dist_tests.erl
- test/gproc_tests.erl
* Replaced some old-style catches with try ... catch for better performance
* Noticed a bug in registration of aggregated counters in combination with await()
* Also noticed that doing await() on aggregated counters wasn't supported
* Fixed and wrote test cases.
> support awaiting aggr ctrs + minor optimizations

- README.md
- doc/overview.edoc
Having badge on top of README.md will allow users to easily get version of latest package published on hex.pm.
> Added hex.pm badge

- src/gproc_dist.erl
- src/gproc_trace.hrl
- test/gproc_dist_tests.erl
This was superficially due to a failed pattern-match in delete_globals(),
but the real issue was that the distr messages for orderly unreg and
cleanup after exit were different. A first quick attempt at fixing
this didn't fix everything, so a slightly laxer test in remove_entry/3
made the test suite pass. However, this means that there is still a
discrepancy that *might* be unsafe, and at the very least is ugly.
> Address issue where crashed process wasn't unregged on remote node

- src/gproc.erl
- src/gproc_dist.erl
- test/gproc_dist_tests.erl
- test/gproc_tests.erl
@spec ensure_reg(Key::key(), Value::value(), Attrs::attrs()) ->
new | updated
@doc Registers a new name or property unless such and entry (by key) has
already been registered by the current process. If `Key` already exists,
the entry will be updated with the given `Value` and `Attrs`.
This function allows the caller to efficiently register an entry without
first checking whether it has already been registered. An exception is
raised if the name or property is already registered by someone else.
@end
> ensure_reg() and ensure_reg_other()

- src/gproc_dist.erl
- test/gproc_dist_tests.erl
Steps to reproduce the bug in original version:
INIT:
node1:
erl -sname n1 -pa ebin -pa deps/*/ebin
node2:
erl -sname n2 -pa ebin -pa deps/*/ebin
node1:
net_adm:ping('n2@carcharodon'), application:ensure_started(gproc), gproc_dist:start_link(all).
node2:
net_adm:ping('n1@carcharodon'), application:ensure_started(gproc), gproc_dist:start_link(all).
TEST:
node1:
gproc:monitor({n, g, test}, standby).                                                                                
=ERROR REPORT==== 7-May-2016::21:09:29 ===
*\* Generic leader gproc_dist terminating 
*\* Last message in was {'$leader_call',
{<0.45.0>,#Ref<0.0.2.214>},
{monitor,{n,g,test},<0.45.0>,standby}}
*\* When Server state == {state,false,true,[]}
*\* Reason for termination == 
*\* {function_clause,[{gproc_dist,insert_reg, …
> fix distributed monitor(Key, standby) when the name is not yet registered

- src/gproc_dist.erl
In my application I have a star topology. So I would like to exclude workers connecting to the central node from becoming cluster leaders as I occasionally observe gproc errors when they elect themselves as leaders.
I hope this pull request is up to standards. First try...
> Exclude nodes as cluster leaders

- src/gproc_dist.erl
- test/gproc_dist_tests.erl
re. issue #145 
Addresses the `case_clause` in `t_sync_cand_dies()`
Increasing overall timeout **may** help, but that's just a guess.
> t_sync_cand_dies() must consider all three nodes. Increased timeout

- src/gproc_dist.erl
- test/gproc_dist_tests.erl
Rewrite gproc_dist:sync() to hopefully be more robust
The old version used gen_leader:leader_call(), which doesn't do well
if the leader dies, or similar things happen. The new solution calls
the local gproc_dist, which remembers the request and casts to the
leader (assuming it's not itself the leader). The leader performs
the sync as before, then casts to the intitial node that the sync
is complete. If a new leader is elected, the other nodes check
pending sync requests and re-initiate them.
Timeouts, which were recently increased, returned to their previous
values.
> Uw rewrite sync

- test/gproc_tests.erl
Use erlang:timestamp/1 instead of (deprecated since r18) erlang:now/1. I don't think it could cause an incompatibility issue since the oldest Travis-CI Erlang version used is R18 anyway.
Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>
> Remove deprecation warning since r18

- src/gproc_dist.erl
- test/gproc_dist_tests.erl
Although CI test failures in `t_master_dies()` did become much less common, one did pop up.
This commit also ensures that pending sync requests are reinitiated if a node becomes leader, or another candidate joins.
> also reinitiate sync when elected/re-elected

- src/gproc_pool.erl
- test/gproc_tests.erl
The previous fix for issue #167 only seems to work for pools of size 1. `del_slot/2` still removed a worker slot if its name was located at the end of the list of workers.
With this change, the worker pool is not lopped off when `auto_size =:= false`.
Also included a unit test that provokes this bug.
> Only shrink the pool when auto_size is true

- .travis.yml
- src/gproc.erl
- src/gproc_lib.erl
- test/gproc_tests.erl
Got rid of a mess with 'monitor'/'monitor[s]' tags in the ETS table
The only 'monitor' tag is used now and that fixes issue #172
Appropriate unit test added
Note:
According to https://docs.travis-ci.com/user/languages/erlang/ Erlang OTP releleases 19.1 and 19.2 aren't supported and should be removed from the Travis configuration file
> Fix issue #172

- src/gproc_dist.erl
I met the following crash
```
14:28:56.141 [error] gproc_dist:747 CRASH REPORT Process gproc_dist with 1 neighbours crashed with reason: no function clause matching gproc_dist:'-mk_broadcast
_insert_vals/1-fun-0-'({{{p,g,{nodename,3}},<0.1206.0>},<0.1206.0>,'cancer3@192.168.2.120'}) line 747
14:28:56.141 [error] gproc_dist:747 Supervisor gproc_sup had child gproc_dist started with gproc_dist:start_link(all) at <0.1215.0> exit with reason no function clause matching gproc_dis
t:'-mk_broadcast_insert_vals/1-fun-0-'({{{p,g,{nodename,3}},<0.1206.0>},<0.1206.0>,'cancer3@192.168.2.120'}) line 747 in context child_terminated
14:28:56.142 [error] gproc_dist:747 CRASH REPORT Process gproc_dist with 1 neighbours crashed with reason: no function clause matching …
```
> Fix function clause matching gproc_dist:mk_broadcast_insert_vals

- src/gproc_pool.erl
in gproc_pool:execute_claim/3. During the course of execute_claim/3 if
Pid dies gproc:reset_counter/1 may crash
** exception error: no match of right hand side value []
in function  gproc:reset_counter1/1 (gproc.erl, line 1895)
in call from gproc:reset_counter/1 (gproc.erl, line 1889)
in call from gproc_pool:execute_claim/3 (gproc_pool.erl, line 548)
in call from gproc_pool:try_claim/2 (gproc_pool.erl, line 501)
in call from gproc_pool:claim_/2 (gproc_pool.erl, line 473)
in call from gproc_pool:claim_w/3 (gproc_pool.erl, line 452)
....
which completely obscures the real crash. With this change you instead
get:
** exception exit: {{shutdown,timeout},
{gen_statem,call,
[<0.14440.1>,
{query,[<<81,0,0,0,25>>,["SELECT pg_sleep(60);",0]],5000},
infinity]}}
in function  gen:do_call/4 (gen.erl, …
> Catch error from gproc:reset_counter/1

- src/gproc.erl
- src/gproc_dist.erl
- src/gproc_int.hrl
- src/gproc_lib.erl
- test/gproc_dist_tests.erl
- test/gproc_test_lib.erl
- test/gproc_tests.erl
From the edoc
* `rc` - 'resource counter', tracks the number of resource properties
with the same name. When the resource count reaches `0`, any triggers
specified using an `on_zero` attribute may be executed (see below).
If `Name` is a tuple, the last element of the name can contain a
wildcard, using the symbol `'\\_'`. This will make the resource
counter keep track of any resources where all elements match except
the last position. For example, `{rc,l,{a,b,'\\_'}}` would keep
track of both `{r,l,{a,b,1}}` and `{r,l,{a,b,2}}`.
> Add wildcard matching in resource counters

- src/gproc.erl
- src/gproc_dist.erl
- src/gproc_lib.erl
- test/gproc_dist_tests.erl
- test/gproc_tests.erl
See PR #163 
Support for resource objects ('r') is made more general, and various inconsistencies around `update_counter()` have been fixed, making it possible to use both names and resources as counters.
Test cases added
> Improved support for 'r' objects

- src/gproc_pool.erl
Before this change a {claim, Pool} message is left in the caller's mailbox for every timeout.
> Flush unwanted timeout messages from gproc_pool:claim/3

- src/gproc_pool.erl
Since [`rand:uniform/1`](https://www.erlang.org/doc/man/rand.html#uniform-1)'s return value is a number in a closed interval (`0 =< N =< Sz`), we shouldn't call it with the pool size + 1, otherwise we will get a non-uniform distribution of results where one of the workers receive substantially more work than all others.
To verify this, I've started a pool with 8 workers using the `random` load-balancing algorithm and measured the frequencies of each PID in `gproc_pool`.
```erlang
PoolName = my_pool.
PoolSize = 8.
ok = gproc_pool:new(PoolName, random, [{size, PoolSize}]).
lists:foreach(fun(I) ->
gproc_pool:add_worker(PoolName, {PoolName, I}, I),
spawn(fun() ->
true = gproc_pool:connect_worker(PoolName, {PoolName, I}),
receive
stop -> ok
end
end),
ok
end, lists:seq(1, PoolSize)). …
```
> fix(gproc_pool): fix `rand:uniform/1` range

- Makefile
- README.md
- doc/README.md
- doc/gproc.md
- doc/gproc_dist.md
- doc/gproc_lib.md
- doc/gproc_ps.md
- rebar.config
- src/gproc.erl
- src/gproc_dist.erl
- src/gproc_lib.erl
- src/gproc_pool.erl
- src/gproc_ps.erl
- test/gproc_dist_tests.erl
- test/gproc_remote_tests.erl
- test/gproc_test_lib.erl
- test/gproc_tests.erl
First sketch of remote registration and `gproc_ps` subscriptions.
The idea is that registering remote pids shouldn't be a problem in itself, but all regs must go through the gproc server, can only have local scope, and the API function should be distinctly only for non-local pids.
**TODO:** add `ensure_...` and `unreg` functions etc. as well as test cases.
> Remote reg and pub/sub

- doc/gproc.md
- patches/stdlib/gen_fsm.erl
- patches/stdlib/gen_server.erl
- src/gproc.erl
Found via `typos --format brief`
> Fix typos again
